# Generated by Django 5.0.4 on 2024-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
