# Generated by Django 5.0.4 on 2024-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_navitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
